import React from 'react';
import { motion } from 'motion/react';
import { 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  Target, 
  Zap, 
  Eye, 
  TrendingUp, 
  ShieldCheck,
  Search,
  ArrowRightLeft,
  BrainCircuit as DecisionEngineIcon,
  Crown,
  Binoculars,
  FlaskConical,
  BarChart3,
  Lightbulb,
  Sparkles,
  ShieldAlert,
  Copy,
  Check,
  Network,
  Anchor
} from 'lucide-react';
import { FinalViralAnalysis } from '../types';
import { copyToClipboard } from '../services/gemini/core';

interface DecisionEngineReportProps {
  data: FinalViralAnalysis;
}

export const DecisionEngineReport: React.FC<DecisionEngineReportProps> = ({ data }) => {
  const [copied, setCopied] = React.useState(false);
  const engine = data; // Already flattened in FinalViralAnalysis
  
  if (!engine.engineVerdict && !(data as any).decisionEngine) return null;

  // Handle both flattened and nested structures if they exist
  const d = (data as any).decisionEngine || {
    dataStatus: engine.engineDataStatus,
    contentType: engine.engineContentType,
    characterStatus: engine.engineCharacterStatus,
    decision: engine.engineVerdict,
    confidence: engine.engineConfidence,
    dominantElement: engine.engineDominantElement,
    sacrificedElements: engine.engineSacrificedElements,
    riskLevel: engine.engineRiskLevel,
    viralScore: engine.viralScore,
    productionWorthiness: engine.engineProductionWorthiness,
    whyThisWorks: engine.engineWhyThisWorks,
    whyThisFails: engine.engineWhyThisFails,
    criticalMoment: engine.engineCriticalMoment,
    structuralProblem: engine.engineStructuralProblem,
    marketContext: engine.engineMarketContext,
    formatSaturation: engine.engineFormatSaturation,
    comparablePerformance: engine.engineComparablePerformance,
    alternativeStrength: engine.engineAlternativeStrength,
    expectedBehavior: engine.engineExpectedBehavior,
    failureScenario: engine.engineFailureScenario,
    improvementDirection: engine.engineImprovementDirection,
    primaryFocus: engine.enginePrimaryFocus,
    secondaryFocus: engine.engineSecondaryFocus,
    suppressedFocus: engine.engineSuppressedFocus,
    reasonForDominanceSelection: engine.engineReasonForDominanceSelection,
    nicheViability: engine.engineNicheClassification,
    nicheViabilityReasoning: engine.engineNicheReasoning,
    pivotSuggestion: engine.enginePivotSuggestion,
    executionPlan: engine.engineExecutionPlan,
    originalIdea: engine.futureStrongerAlternative, // For Point 9
    strongerAlternative: engine.futureStrongerAlternative,
    higherPotential: engine.futureHigherPotential,
    outcomeChanger: engine.futureOutcomeChanger,
    why: engine.futureWhy
  };

  const getVerdictColor = (verdict?: string) => {
    switch (verdict) {
      case 'KEEP': return 'text-green-500 bg-green-500/10 border-green-500/20';
      case 'MODIFY': return 'text-amber-500 bg-amber-500/10 border-amber-500/20';
      case 'REPLACE': return 'text-red-500 bg-red-500/10 border-red-500/20';
      default: return 'text-gray-500 bg-gray-500/10 border-gray-500/20';
    }
  };

  const getStatusIcon = (status?: string) => {
    switch (status) {
      case 'REAL': return <ShieldCheck className="w-4 h-4 text-green-500" />;
      case 'INFERRED': return <TrendingUp className="w-4 h-4 text-blue-500" />;
      case 'NO_DATA': return <ShieldAlert className="w-4 h-4 text-red-500" />;
      default: return null;
    }
  };

  const handleCopyReport = async () => {
    const reportText = `
🧠 INTELLIGENCE REPORT: VIRAL DECISION ENGINE
-------------------------------------------
DECISION: ${d.decision || 'UNVERIFIED'}
CONFIDENCE: ${d.confidence || 'LOW'}
RISK LEVEL: ${d.riskLevel || 'HIGH'}
CONTENT TYPE: ${d.contentType || 'N/A'}
VIRAL SCORE: ${d.viralScore || 'UNVERIFIED'}
PRODUCTION WORTHINESS: ${d.productionWorthiness || 'UNVERIFIED'}
DATA STATUS: ${d.dataStatus || 'NO_DATA'}

1. STRATEGIC REASONING
- WHY IT WORKS: ${(d.whyThisWorks || []).join(', ')}
- WHY IT FAILS: ${(d.whyThisFails || []).join(', ')}
- CRITICAL MOMENT: ${d.criticalMoment || 'N/A'}
- STRUCTURAL PROBLEM: ${d.structuralProblem || 'NONE'}

2. MARKET & PERFORMANCE
- CONTEXT: ${d.marketContext || 'N/A'}
- SATURATION: ${d.formatSaturation || 'N/A'}
- EXPECTED BEHAVIOR: ${d.expectedBehavior || 'N/A'}
- FAILURE SCENARIO: ${d.failureScenario || 'N/A'}

3. TRANSFORMATION PLAN
- PRIMARY FOCUS: ${d.primaryFocus || 'N/A'}
- EXECUTION: ${d.executionPlan || 'N/A'}
- REASONING: ${d.reasonForDominanceSelection || 'N/A'}

4. NICHE VIABILITY
- STATUS: ${d.nicheViability || 'ALIVE'}
- REASONING: ${d.nicheViabilityReasoning || 'N/A'}

5. ALTERNATIVE STRATEGY
- STRONGER ALTERNATIVE: ${d.strongerAlternative || 'N/A'}
- WHY: ${d.why || 'N/A'}
- OUTCOME CHANGER: ${d.outcomeChanger || 'N/A'}

-------------------------------------------
ANALYSIS GENERATED BY DECISION ENGINE PROTOCOL V4.0.5
    `.trim();

    const success = await copyToClipboard(reportText);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* COPY ACTION FOR MOBILE */}
      <div className="flex justify-end sticky top-0 z-10 pt-2 pointer-events-none">
        <button
          onClick={handleCopyReport}
          className={`pointer-events-auto flex items-center gap-2 px-4 py-2 rounded-full border shadow-lg transition-all ${
            copied 
              ? 'bg-green-500 border-green-400 text-white scale-105 shadow-green-500/20' 
              : 'bg-indigo-600 border-indigo-400 text-white hover:bg-indigo-500 active:scale-95 shadow-indigo-500/20'
          }`}
        >
          {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          <span className="text-sm font-bold">{copied ? 'Copiato!' : 'Copia Report'}</span>
        </button>
      </div>

      {/* 0) CONTENT HIERARCHY (PRE-GENERATION) */}
      {data.contentHierarchy && (
        <section className="bg-indigo-950/40 border border-indigo-500/20 rounded-2xl p-6 backdrop-blur-xl relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Network className="w-24 h-24 text-indigo-400" />
          </div>
          
          <div className="flex items-center gap-3 mb-6 relative z-10">
            <Network className="w-6 h-6 text-indigo-400" />
            <h3 className="text-xl font-bold text-white tracking-tight">0. Content Hierarchy (Pre-Generation)</h3>
            <div className="ml-auto flex items-center gap-2 px-3 py-1 bg-indigo-500/10 rounded-full border border-indigo-500/20">
              <ShieldCheck className="w-3 h-3 text-indigo-400" />
              <span className="text-xs font-mono uppercase tracking-widest text-indigo-300">Semantic Map</span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 relative z-10">
            <div className="space-y-4">
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-indigo-400/60 font-bold mb-1 block">Content Type</span>
                <span className="text-lg font-bold text-white">{data.contentHierarchy.contentType}</span>
              </div>
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-amber-400/60 font-bold mb-1 block">Primary Subject</span>
                <span className="text-lg font-bold text-white">{data.contentHierarchy.primarySubject}</span>
              </div>
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-emerald-400/60 font-bold mb-1 block">Dominant Purpose</span>
                <span className="text-lg font-bold text-white">{data.contentHierarchy.dominantPurpose}</span>
              </div>
            </div>
            
            <div className="space-y-4">
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl h-full flex flex-col justify-between">
                <div>
                  <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold mb-2 block">Elements & Hooks</span>
                  <div className="flex flex-wrap gap-2 mb-3">
                    {data.contentHierarchy.secondarySubjects?.map((s: string, i: number) => (
                      <span key={i} className="text-xs px-2 py-1 rounded bg-black/40 border border-white/10 text-white/80">{s} (Secondary)</span>
                    ))}
                    {data.contentHierarchy.hookCandidates?.map((s: string, i: number) => (
                      <span key={i} className="text-xs px-2 py-1 rounded bg-indigo-500/10 border border-indigo-500/20 text-indigo-300">{s} (Hook)</span>
                    ))}
                  </div>
                </div>
                
                {data.contentHierarchy.forbiddenDominantElements && data.contentHierarchy.forbiddenDominantElements.length > 0 && (
                  <div className="mt-4 border-t border-red-500/20 pt-3">
                    <span className="text-[10px] uppercase tracking-widest text-red-500/60 font-bold mb-2 flex items-center gap-1">
                      <ShieldAlert className="w-3 h-3" /> Forbidden Dominance
                    </span>
                    <div className="flex flex-wrap gap-2">
                       {data.contentHierarchy.forbiddenDominantElements.map((s: string, i: number) => (
                        <span key={i} className="text-xs px-2 py-1 rounded bg-red-500/10 border border-red-500/20 text-red-400 line-through">{s}</span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>
      )}

      {/* 0.1) PRIMARY PURPOSE LOCK (PRE-ASSET GENERATION) */}
      {data.primaryPurposeLock && (
        <section className={`border rounded-2xl p-6 backdrop-blur-xl relative overflow-hidden ${
          data.primaryPurposeLock.lockStatus === 'PASS' 
            ? 'bg-blue-950/40 border-blue-500/20' 
            : 'bg-orange-950/40 border-orange-500/20'
        }`}>
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <DecisionEngineIcon className="w-24 h-24 text-blue-400" />
          </div>
          
          <div className="flex items-center gap-3 mb-6 relative z-10">
            {data.primaryPurposeLock.lockStatus === 'PASS' ? (
              <ShieldCheck className="w-6 h-6 text-blue-400" />
            ) : (
              <ShieldAlert className="w-6 h-6 text-orange-400" />
            )}
            <h3 className="text-xl font-bold text-white tracking-tight">0.1 Primary Purpose Lock (Pre-Asset Gen)</h3>
            <div className={`ml-auto flex items-center gap-2 px-3 py-1 rounded-full border ${
              data.primaryPurposeLock.lockStatus === 'PASS' ? 'bg-blue-500/10 border-blue-500/20' : 'bg-orange-500/10 border-orange-500/20'
            }`}>
              <span className={`text-xs font-mono uppercase tracking-widest ${
                data.primaryPurposeLock.lockStatus === 'PASS' ? 'text-blue-300' : 'text-orange-300'
              }`}>
                {data.primaryPurposeLock.lockStatus}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 relative z-10">
            {/* Elements Classification */}
            <div className="lg:col-span-2 space-y-3">
              <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold block">Elements Role Classification</span>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {data.primaryPurposeLock.elementsClassification?.map((item, i) => (
                  <div key={i} className="p-3 bg-white/5 border border-white/10 rounded-lg">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm font-bold text-white">{item.element}</span>
                      <span className={`text-[9px] px-1.5 py-0.5 rounded font-bold uppercase ${
                        item.role === 'CORE_DRIVER' ? 'bg-emerald-500/20 text-emerald-400' :
                        item.role === 'SUPPORT' ? 'bg-indigo-500/20 text-indigo-400' :
                        'bg-orange-500/20 text-orange-400'
                      }`}>
                        {item.role}
                      </span>
                    </div>
                    <p className="text-[10px] text-zinc-400 leading-tight">{item.justification}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Constraints */}
            <div className="space-y-4">
              <div>
                <span className="text-[10px] uppercase tracking-widest text-red-400/60 font-bold mb-2 flex items-center gap-1">
                   <ShieldAlert className="w-3 h-3" /> Forbidden as Hook
                </span>
                <div className="flex flex-wrap gap-2">
                   {data.primaryPurposeLock.hookConstraint?.forbiddenElements?.map((s, i) => (
                    <span key={i} className="text-[11px] px-2 py-1 rounded bg-red-500/10 border border-red-500/20 text-red-300">{s}</span>
                  ))}
                </div>
              </div>
              
              <div className="p-3 bg-emerald-500/5 border border-emerald-500/20 rounded-xl">
                 <span className="text-[10px] uppercase tracking-widest text-emerald-400/60 font-bold mb-1 block">Opening Focus (0-3s)</span>
                 <p className="text-xs text-emerald-100 italic">"{data.primaryPurposeLock.openingConstraint}"</p>
              </div>
              
              {data.primaryPurposeLock.scrappedElement && (
                <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl">
                  <span className="text-[10px] uppercase tracking-widest text-red-500/60 font-bold mb-1 block">Scrapped Element</span>
                  <span className="text-xs text-red-400 font-bold">{data.primaryPurposeLock.scrappedElement}</span>
                </div>
              )}
            </div>
          </div>
        </section>
      )}

      {/* 0.2) FUNCTIONAL ROLE LOCK (NARRATIVE ASIS) */}
      {data.functionalRoleLock && (
        <section className={`border rounded-2xl p-6 backdrop-blur-xl relative overflow-hidden ${
          data.functionalRoleLock.lockStatus === 'PASS' 
            ? 'bg-purple-950/40 border-purple-500/20' 
            : 'bg-red-950/40 border-red-500/20'
        }`}>
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <TrendingUp className="w-24 h-24 text-purple-400" />
          </div>
          
          <div className="flex items-center gap-3 mb-6 relative z-10">
            <Zap className="w-6 h-6 text-purple-400" />
            <h3 className="text-xl font-bold text-white tracking-tight">0.2 Functional Role Lock (Narrative Axis)</h3>
            <div className={`ml-auto flex items-center gap-2 px-3 py-1 rounded-full border ${
              data.functionalRoleLock.lockStatus === 'PASS' ? 'bg-purple-500/10 border-purple-500/20' : 'bg-red-500/10 border-red-500/20'
            }`}>
              <span className={`text-xs font-mono uppercase tracking-widest ${
                data.functionalRoleLock.lockStatus === 'PASS' ? 'text-purple-300' : 'text-red-300'
              }`}>
                {data.functionalRoleLock.lockStatus}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 relative z-10">
            <div className="space-y-4">
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-purple-400/60 font-bold mb-1 block">Primary Hook Emotion</span>
                <span className="text-lg font-bold text-white uppercase tracking-wider">{data.functionalRoleLock.primaryEmotion}</span>
              </div>
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-zinc-400 font-bold mb-1 block">Implicit Emotion Source</span>
                <div className="flex items-center gap-2">
                  <span className="text-lg font-bold text-white">{data.functionalRoleLock.implicitElement}</span>
                  <span className={`text-[9px] px-1.5 py-0.5 rounded font-bold uppercase ${
                    data.functionalRoleLock.emotionSourceRole === 'CORE_DRIVER' ? 'bg-emerald-500/20 text-emerald-400' :
                    data.functionalRoleLock.emotionSourceRole === 'SUPPORT' ? 'bg-indigo-500/20 text-indigo-400' :
                    'bg-orange-500/20 text-orange-400'
                  }`}>
                    {data.functionalRoleLock.emotionSourceRole}
                  </span>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                 <span className="text-[10px] uppercase tracking-widest text-zinc-400 font-bold mb-2 block">Narrative reasoning</span>
                 <p className="text-sm text-zinc-300 leading-relaxed italic">"{data.functionalRoleLock.passReasoning}"</p>
              </div>
              
              {data.functionalRoleLock.correctiveDirection && data.functionalRoleLock.lockStatus === 'FAIL' && (
                <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                  <span className="text-[10px] uppercase tracking-widest text-red-400 font-bold mb-1 block">Corrective Action Required</span>
                  <p className="text-sm text-red-200 font-medium">{data.functionalRoleLock.correctiveDirection}</p>
                </div>
              )}
            </div>
          </div>
        </section>
      )}

      {/* 0.3) IDEA ANCHOR LOCK (CONCEPT SOURCE) */}
      {data.ideaAnchorLock && (
        <section className={`border rounded-2xl p-6 backdrop-blur-xl relative overflow-hidden ${
          data.ideaAnchorLock.lockStatus === 'PASS' 
            ? 'bg-indigo-950/40 border-indigo-500/20' 
            : 'bg-red-950/40 border-red-500/20'
        }`}>
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Anchor className="w-24 h-24 text-indigo-400" />
          </div>
          
          <div className="flex items-center gap-3 mb-6 relative z-10">
            <Anchor className="w-6 h-6 text-indigo-400" />
            <h3 className="text-xl font-bold text-white tracking-tight">0.3 Idea Anchor Lock (Concept Integrity)</h3>
            <div className={`ml-auto flex items-center gap-2 px-3 py-1 rounded-full border ${
              data.ideaAnchorLock.lockStatus === 'PASS' ? 'bg-indigo-500/10 border-indigo-500/20' : 'bg-red-500/10 border-red-500/20'
            }`}>
              <span className={`text-xs font-mono uppercase tracking-widest ${
                data.ideaAnchorLock.lockStatus === 'PASS' ? 'text-indigo-300' : 'text-red-300'
              }`}>
                {data.ideaAnchorLock.lockStatus}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-6 relative z-10">
            <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
               <span className="text-[10px] uppercase tracking-widest text-indigo-400/60 font-bold mb-2 block">Central Concept</span>
               <p className="text-lg font-bold text-white italic">"{data.ideaAnchorLock.centralIdea}"</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-zinc-400 font-bold mb-1 block">Anchor Source</span>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-bold text-white">{data.ideaAnchorLock.anchorSource}</span>
                  <span className={`text-[9px] px-1.5 py-0.5 rounded font-bold uppercase ${
                    data.ideaAnchorLock.anchorRole === 'CORE_DRIVER' ? 'bg-emerald-500/20 text-emerald-400' :
                    data.ideaAnchorLock.anchorRole === 'SUPPORT' ? 'bg-indigo-500/20 text-indigo-400' :
                    'bg-orange-500/20 text-orange-400'
                  }`}>
                    {data.ideaAnchorLock.anchorRole}
                  </span>
                </div>
              </div>

              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-zinc-400 font-bold mb-1 block">Dependency Removal Test</span>
                <div className={`flex items-center gap-2 font-bold ${
                  data.ideaAnchorLock.dependencyTest === 'PASS' ? 'text-emerald-400' : 'text-red-400'
                }`}>
                  {data.ideaAnchorLock.dependencyTest === 'PASS' ? <ShieldCheck className="w-4 h-4" /> : <ShieldAlert className="w-4 h-4" />}
                  <span className="text-sm uppercase tracking-wide">{data.ideaAnchorLock.dependencyTest}</span>
                </div>
              </div>

              <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-zinc-400 font-bold mb-1 block">Full Independence</span>
                <span className={`text-sm font-bold ${data.ideaAnchorLock.isIndependent ? 'text-emerald-400' : 'text-red-400'}`}>
                  {data.ideaAnchorLock.isIndependent ? 'VERIFIED (Autonomous)' : 'FAILED (Parasitic Concept)'}
                </span>
              </div>
            </div>

            {data.ideaAnchorLock.violationReason && data.ideaAnchorLock.lockStatus === 'FAIL' && (
              <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                <span className="text-[10px] uppercase tracking-widest text-red-400 font-bold mb-1 block">Anchor Violation Details</span>
                <p className="text-sm text-red-200 font-medium">{data.ideaAnchorLock.violationReason}</p>
              </div>
            )}
          </div>
        </section>
      )}

      {/* 0.5) DOMINANCE CHECK (POST-GENERATION) */}
      {data.dominanceCheck && (
        <section className={`border rounded-2xl p-6 backdrop-blur-xl relative overflow-hidden ${
          data.dominanceCheck.pass 
            ? 'bg-green-950/40 border-green-500/20' 
            : 'bg-red-950/40 border-red-500/20'
        }`}>
          <div className="absolute top-0 right-0 p-4 opacity-10">
            {data.dominanceCheck.pass ? 
              <CheckCircle2 className="w-24 h-24 text-green-400" /> : 
              <ShieldAlert className="w-24 h-24 text-red-400" />
            }
          </div>
          
          <div className="flex items-center gap-3 mb-6 relative z-10">
            {data.dominanceCheck.pass ? 
              <ShieldCheck className="w-6 h-6 text-green-400" /> : 
              <ShieldAlert className="w-6 h-6 text-red-500" />
            }
            <h3 className="text-xl font-bold text-white tracking-tight">Post-Generation Coherence Validation</h3>
            <div className={`ml-auto flex items-center gap-2 px-3 py-1 rounded-full border ${
              data.dominanceCheck.pass ? 'bg-green-500/10 border-green-500/20' : 'bg-red-500/10 border-red-500/20'
            }`}>
              <span className={`text-xs font-mono uppercase tracking-widest ${
                data.dominanceCheck.pass ? 'text-green-300' : 'text-red-300'
              }`}>
                {data.dominanceCheck.pass ? 'PASSED' : 'FAILED'}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 relative z-10">
            <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
               <span className={`text-[10px] uppercase tracking-widest font-bold mb-1 block ${
                 data.dominanceCheck.pass ? 'text-green-400/60' : 'text-red-400/60'
               }`}>Detected Dominant Element</span>
               <span className={`text-lg font-bold ${
                 data.dominanceCheck.pass ? 'text-white' : 'text-red-300'
               }`}>{data.dominanceCheck.dominantElement}</span>
               
               <div className="mt-2 text-sm text-white/50 flex items-center gap-1">
                 Expected: <span className="text-white/80">{data.dominanceCheck.expectedPrimary}</span>
               </div>
            </div>
            
            <div className="p-4 bg-white/5 border border-white/10 rounded-xl flex flex-col justify-center">
              <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold mb-1 block">Reason</span>
              <span className="text-sm font-bold text-white/80 break-words">{data.dominanceCheck.reason}</span>
              {data.dominanceCheck.details && (
                <p className="mt-2 text-xs text-white/60">{data.dominanceCheck.details}</p>
              )}
            </div>
          </div>
          
          {!data.dominanceCheck.pass && data.dominanceCheck.severity === 'HIGH' && (
            <div className="mt-4 p-3 bg-red-500/20 border border-red-500/30 rounded-lg flex items-start gap-2 relative z-10">
              <AlertTriangle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
              <div>
                <span className="text-sm font-bold text-red-200 block">Critical Violation Detected</span>
                <span className="text-xs text-red-300/80">The system generated an output that violates the core semantic hierarchy. This heavily impacted the final viral score. Do not use this output without manual correction.</span>
              </div>
            </div>
          )}
        </section>
      )}

      {/* 1) CORE DECISION BLOCK */}
      <section className="bg-black/40 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
        <div className="flex items-center gap-3 mb-6">
          <DecisionEngineIcon className="w-6 h-6 text-purple-400" />
          <h3 className="text-xl font-bold text-white tracking-tight">1. Core Decision Block</h3>
          <div className="ml-auto flex items-center gap-2 px-3 py-1 bg-white/5 rounded-full border border-white/10">
            {getStatusIcon(d.dataStatus)}
            <span className="text-xs font-mono uppercase tracking-widest text-white/50">{d.dataStatus || 'UNVERIFIED'}</span>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className={`p-4 rounded-xl border ${getVerdictColor(d.decision)} flex flex-col items-center justify-center text-center`}>
            <span className="text-[10px] uppercase tracking-widest opacity-60 mb-1 font-bold">Decision</span>
            <span className="text-2xl font-black">{d.decision || 'UNVERIFIED'}</span>
          </div>

          <div className="p-4 rounded-xl bg-white/5 border border-white/10 flex flex-col items-center justify-center text-center">
            <span className="text-[10px] uppercase tracking-widest text-white/40 mb-1 font-bold">Confidence</span>
            <span className={`text-xl font-bold ${
              d.confidence === 'HIGH' ? 'text-green-400' : d.confidence === 'MEDIUM' ? 'text-amber-400' : 'text-red-400'
            }`}>{d.confidence || 'LOW'}</span>
          </div>

          <div className="p-4 rounded-xl bg-white/5 border border-white/10 flex flex-col items-center justify-center text-center">
            <span className="text-[10px] uppercase tracking-widest text-white/40 mb-1 font-bold">Risk Level</span>
            <span className={`text-xl font-bold ${
              d.riskLevel === 'LOW' ? 'text-green-400' : d.riskLevel === 'MEDIUM' ? 'text-amber-400' : 'text-red-400'
            }`}>{d.riskLevel || 'HIGH'}</span>
          </div>

          <div className="p-4 rounded-xl bg-white/5 border border-white/10 flex flex-col items-center justify-center text-center">
            <span className="text-[10px] uppercase tracking-widest text-white/40 mb-1 font-bold">Content Type</span>
            <span className="text-sm font-bold text-white uppercase tracking-tight truncate w-full">{d.contentType || 'N/A'}</span>
          </div>
        </div>

        <div className="mt-4 grid grid-cols-2 gap-4">
          <div className="p-3 bg-white/5 border border-white/10 rounded-xl">
            <div className="flex items-center gap-2 mb-2">
              <Crown className="w-3 h-3 text-yellow-400" />
              <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold">Dominant Element</span>
            </div>
            <span className="text-sm font-mono text-purple-300">{d.dominantElement || 'NONE'}</span>
          </div>
          <div className="p-3 bg-white/5 border border-white/10 rounded-xl">
            <div className="flex items-center gap-2 mb-2">
              <Target className="w-3 h-3 text-red-400" />
              <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold">Sacrificed Elements</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {d.sacrificedElements?.map((el, i) => (
                <span key={i} className="text-[10px] bg-red-500/10 text-red-400 px-2 py-0.5 rounded border border-red-500/20 uppercase">
                  {el}
                </span>
              )) || <span className="text-[10px] text-white/20 italic">None</span>}
            </div>
          </div>
        </div>
      </section>

      {/* 2) STRATEGIC REASONING */}
      <section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-black/40 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
          <div className="flex items-center gap-2 mb-4">
            <Lightbulb className="w-4 h-4 text-yellow-400" />
            <h4 className="text-sm font-bold text-white uppercase tracking-widest">2. Strategic Reasoning</h4>
          </div>
          <div className="space-y-4">
            <div>
              <span className="text-[10px] uppercase tracking-widest text-green-400/60 font-bold mb-2 block">Why this works</span>
              <ul className="space-y-1">
                {d.whyThisWorks?.map((point, i) => (
                  <li key={i} className="flex gap-2 text-sm text-white/70">
                    <span className="text-green-500">•</span>
                    {point}
                  </li>
                )) || <li className="text-white/30 italic text-sm">No analysis available</li>}
              </ul>
            </div>
            <div>
              <span className="text-[10px] uppercase tracking-widest text-red-400/60 font-bold mb-2 block">Why this fails</span>
              <ul className="space-y-1">
                {d.whyThisFails?.map((point, i) => (
                  <li key={i} className="flex gap-2 text-sm text-white/70">
                    <span className="text-red-500">•</span>
                    {point}
                  </li>
                )) || <li className="text-white/30 italic text-sm">No analysis available</li>}
              </ul>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <div className="bg-red-500/5 border border-red-500/10 rounded-2xl p-5 backdrop-blur-xl">
            <div className="flex items-center gap-2 mb-3">
              <Zap className="w-4 h-4 text-red-500" />
              <span className="text-[10px] uppercase tracking-widest text-red-400 font-bold">Critical Moment</span>
            </div>
            <p className="text-sm text-white font-medium">{d.criticalMoment || 'Not identified'}</p>
          </div>
          <div className="bg-amber-500/5 border border-amber-500/10 rounded-2xl p-5 backdrop-blur-xl">
            <div className="flex items-center gap-2 mb-3">
              <AlertTriangle className="w-4 h-4 text-amber-500" />
              <span className="text-[10px] uppercase tracking-widest text-amber-400 font-bold">Structural Problem</span>
            </div>
            <p className="text-sm text-white font-medium">{d.structuralProblem || 'No structural issues detected'}</p>
          </div>
        </div>
      </section>

      {/* 3) EXTERNAL VALIDATION & 4) PERFORMANCE LOGIC */}
      <section className="bg-black/40 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
        <div className="flex items-center gap-3 mb-6">
          <Binoculars className="w-5 h-5 text-blue-400" />
          <h4 className="text-sm font-bold text-white uppercase tracking-widest">3 & 4. Reality & Performance Hub</h4>
          {d.dataStatus === 'NO_DATA' && (
            <span className="ml-auto text-[10px] font-mono text-red-400 bg-red-400/10 px-2 py-0.5 rounded border border-red-400/20">
              NO REAL VALIDATION POSSIBLE
            </span>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <div className="space-y-4">
              <div className="flex flex-col gap-1">
                <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold">Market Context</span>
                <p className="text-sm text-white/80 italic">{d.marketContext || 'N/A'}</p>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-[10px] uppercase tracking-widest text-white/40 font-bold">Format Saturation</span>
                <p className="text-sm text-white/80">{d.formatSaturation || 'N/A'}</p>
              </div>
            </div>
          </div>
          
          <div className="space-y-4 border-l border-white/5 pl-8">
            <div className="flex flex-col gap-1">
              <span className="text-[10px] uppercase tracking-widest text-blue-400/60 font-bold">Expected Behavior</span>
              <p className="text-sm text-white/80">{d.expectedBehavior || 'N/A'}</p>
            </div>
            <div className="flex flex-col gap-1 border-t border-white/5 pt-4">
              <span className="text-[10px] uppercase tracking-widest text-red-500/60 font-bold">Failure Scenario</span>
              <p className="text-sm text-white/80">{d.failureScenario || 'N/A'}</p>
            </div>
          </div>
        </div>
      </section>

      {/* 5) DOMINANCE ENGINE & 6) TRANSFORMATION */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 bg-black/40 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-4 h-4 text-purple-400" />
            <h4 className="text-sm font-bold text-white uppercase tracking-widest">5 & 6. Transformation Blueprint</h4>
          </div>
          
          <div className="grid grid-cols-2 gap-6">
            <div className="space-y-3">
              <div className="flex flex-col gap-1">
                <span className="text-[10px] text-purple-400/60 uppercase font-bold tracking-widest">Primary Focus</span>
                <p className="text-xs text-white/70">{d.primaryFocus || 'None'}</p>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-[10px] text-white/30 uppercase font-bold tracking-widest">Suppressed</span>
                <p className="text-xs text-white/40">{d.suppressedFocus || 'None'}</p>
              </div>
            </div>
            <div className="bg-white/5 rounded-xl p-4 border border-white/10">
              <span className="text-[10px] text-white/40 uppercase font-bold tracking-widest mb-2 block">Reason for dominance Selection</span>
              <p className="text-xs text-white/80 leading-relaxed italic">"{d.reasonForDominanceSelection || 'N/A'}"</p>
            </div>
          </div>

          {d.executionPlan && (
            <div className="mt-6 p-4 bg-purple-500/10 border border-purple-500/20 rounded-xl">
              <span className="text-[10px] text-purple-400 uppercase font-bold tracking-widest mb-2 block">Execution Plan</span>
              <p className="text-sm text-white/90 leading-relaxed whitespace-pre-wrap">{d.executionPlan}</p>
            </div>
          )}
        </div>

        <div className="bg-gradient-to-br from-purple-500/20 to-blue-500/20 border border-white/10 rounded-2xl p-6 flex flex-col justify-center">
          <div className="text-center mb-4">
            <ArrowRightLeft className="w-8 h-8 text-white mx-auto mb-2 opacity-50" />
            <span className="text-[10px] text-white/60 uppercase font-bold tracking-widest">Evolution Decision</span>
          </div>
          <div className="text-center">
            <span className="text-2xl font-black text-white tracking-widest block mb-1">ENHANCE</span>
            <p className="text-[10px] text-white/40 font-mono italic">Strategic Improvement</p>
          </div>
        </div>
      </section>

      {/* 7, 8, 9, 10 Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* 7) PRODUCTION WORTHINESS */}
        <div className="bg-black/40 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
          <div className="flex items-center gap-2 mb-4">
            <FlaskConical className="w-4 h-4 text-green-400" />
            <h4 className="text-sm font-bold text-white uppercase tracking-widest">7. Production Worthiness</h4>
          </div>
          <div className="flex items-center gap-4 mb-4">
            <span className={`text-xl font-black px-4 py-1 rounded-lg border ${
              d.productionWorthiness === 'YES' ? 'text-green-400 border-green-400/20 bg-green-400/10' : 
              d.productionWorthiness === 'NO' ? 'text-red-400 border-red-400/20 bg-red-400/10' :
              'text-amber-400 border-amber-400/20 bg-amber-400/10'
            }`}>
              {d.productionWorthiness || 'UNVERIFIED'}
            </span>
            <p className="text-xs text-white/60 font-medium italic">"{d.improvementDirection || 'Strategic potential unverified'}"</p>
          </div>
        </div>

        {/* 8) NICHE VIABILITY */}
        <div className="bg-black/40 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
          <div className="flex items-center gap-2 mb-4">
            <BarChart3 className="w-4 h-4 text-orange-400" />
            <h4 className="text-sm font-bold text-white uppercase tracking-widest">8. Niche Viability</h4>
          </div>
          <div className="flex items-center gap-4 mb-4">
            <span className={`text-xl font-black px-4 py-1 rounded-lg border ${
              d.nicheViability === 'ALIVE' ? 'text-green-400 border-green-400/20 bg-green-400/10' : 
              d.nicheViability === 'DEAD' ? 'text-gray-400 border-gray-400/20 bg-gray-400/10' :
              d.nicheViability === 'SATURATED' ? 'text-amber-400 border-amber-400/20 bg-amber-400/10' :
              'text-red-400 border-red-400/20 bg-red-400/10'
            }`}>
              {d.nicheViability || 'ALIVE'}
            </span>
             <p className="text-xs text-white/60 leading-tight">{d.nicheViabilityReasoning || 'Healthy niche observed.'}</p>
          </div>
        </div>
      </div>
      
      {/* 9) FUTURE VALUE COMPARISON */}
      <section className="bg-gradient-to-r from-blue-600/10 to-indigo-600/10 border border-white/5 rounded-2xl p-6 backdrop-blur-xl">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <ArrowRightLeft className="w-5 h-5 text-indigo-400" />
            <h4 className="text-sm font-bold text-white uppercase tracking-widest">9. Future Value Comparison</h4>
          </div>
          <div className="bg-indigo-500/20 text-indigo-300 text-[10px] font-bold px-3 py-1 rounded-full border border-indigo-500/30 uppercase tracking-widest">
            {d.higherPotential === 'ALTERNATIVE' ? 'PIVOT RECOMMENDED' : 'OPTIMIZING CORE'}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-5 gap-6 items-center">
          <div className="md:col-span-2 space-y-4">
            <div className="p-4 bg-white/5 border border-white/10 rounded-xl relative overflow-hidden">
              <div className="absolute top-0 right-0 p-1 px-2 bg-white/5 border-b border-l border-white/10 rounded-bl-lg">
                <span className="text-[8px] uppercase tracking-widest text-white/30 font-bold">Original</span>
              </div>
              <p className="text-sm text-white/50">{d.originalIdea || 'Core concept as submitted'}</p>
            </div>
            
            <div className="p-4 bg-indigo-500/5 border border-indigo-500/20 rounded-xl relative overflow-hidden ring-1 ring-indigo-500/30">
               <div className="absolute top-0 right-0 p-1 px-2 bg-indigo-500/20 border-b border-l border-indigo-500/30 rounded-bl-lg">
                <span className="text-[8px] uppercase tracking-widest text-indigo-300 font-bold">Stronger Alternative</span>
              </div>
              <p className="text-sm text-white font-medium">{d.strongerAlternative || 'No alternative proposed'}</p>
            </div>
          </div>

          <div className="flex flex-col items-center justify-center">
            <div className="w-10 h-10 rounded-full bg-white/5 border border-white/10 flex items-center justify-center">
              <span className="text-xs font-black text-white/40 italic">VS</span>
            </div>
          </div>

          <div className="md:col-span-2 bg-black/40 rounded-xl p-5 border border-white/5">
            <div className="space-y-4">
              <div>
                 <span className="text-[10px] uppercase tracking-widest text-indigo-400 font-bold mb-1 block">Outcome Changer</span>
                 <p className="text-xs text-white/70 italic leading-relaxed">"{d.outcomeChanger || 'Strategic shift for higher viral potential.'}"</p>
              </div>
              <div className="pt-4 border-t border-white/5">
                <span className="text-[10px] uppercase tracking-widest text-indigo-400 font-bold mb-1 block">Why?</span>
                <p className="text-xs text-white/70 leading-relaxed">{d.why || 'Higher structural engagement signals.'}</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
        <div className="flex items-center gap-2 mb-2">
          <ShieldAlert className="w-4 h-4 text-red-500" />
          <span className="text-xs font-bold text-red-400 uppercase tracking-widest">Hard Neutrality Check</span>
        </div>
        <p className="text-xs text-red-400/80 italic font-medium leading-relaxed">
          "{d.engineHonestyStatement || 'I am a strict analytical engine. This analysis is an estimation based on known patterns and is NOT a guarantee of performance.'}"
        </p>
      </div>
    </div>
  );
};
